
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://47.52.128.159:3306/myinsuredb
    driver-class-name: com.mysql.jdbc.Driver
    username: myinsuredb
    password: 123




mybatis:
  type-aliases-package: java.util


zuul:
  routes:
    goods-service: /gateway/goods/**
    order-service: /gateway/order/**
    buy-insurance-service: /gateway/buy/**
  ignored-patterns: /*-service/**
  sensitive-headers:
