
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: custlog-service
  thymeleaf:
   encoding: UTF-8
   cache: false
   mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://47.52.128.159:3306/myinsuredb
    driver-class-name: com.mysql.jdbc.Driver
    username: myinsuredb
    password: 123

  redis:
    host: 192.168.242.129
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 10000



mybatis:
  type-aliases-package: java.util