server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: bgmanage-service
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://47.52.128.159:3306/myinsuredb
    username: myinsuredb
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    #\u914D\u7F6E\u5DE5\u4F5C\u6D41
  activiti:
    database-schema: update #\u6570\u636E\u8868\u7684\u751F\u6210\u7B56\u7565\uFF0C\u5982\u679C\u6570\u636E\u5B58\u5728\uFF0C\u5C31\u7EE7\u7EED\u4F7F\u7528\uFF0C\u5982\u679C\u4E0D\u5B58\u5728\uFF0C\u5219\u521B\u5EFA
    check-process-definitions: false #\u4E0D\u8981\u68C0\u6D4B\u5F53\u524D\u5DE5\u7A0B\u4E2D\u662F\u5305\u542Bbpmn\u6587\u4EF6
mybatis:
  type-aliases-package: java.util

