#买保险的服务
#端口8899
server:
  port: 8899
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#服务名称buy-insurance-service
spring:
  application:
    name: buy-insurance-service
#配置thymeleaf
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  #配置数据库连接信息
  datasource:
    url: jdbc:mysql://47.52.128.159:3306/myinsuredb #?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: myinsuredb
    password: 123
    tomcat:
      max-idle: 5000
      min-idle: 2300
      max-wait: 10000
      max-active: 5000
  #配置activiti
  activiti:
    database-schema: update
    check-process-definitions: false
  #文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
#mybaits的别名
mybatis:
  type-aliases-package: java.util

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

